# Basic Information 
title: Yuchen Zhang
title_zh: 张宇琛
position: Ph.D. Student
affiliation: Rensselaer Polytechnic Institute, Computer Science
affiliation_link: https://www.rpi.edu/
# affiliation_logo: ./assets/img/sic.png
email: zhangy94(at)rpi.edu
# email2: miaoranzhang(at)gmail.com

# Search Engine Optimization (SEO)
keywords: yuchen zhang, zhang yuchen, yuchenzhang, zhangyuchen

# The option is used to enable the Johns Hopkins template.
#enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=QFkTtL8AAAAJ&hl=en
github_link: https://github.com/YCZZZZZZ
# cv_link: ./assets/doc/CV.pdf
linkedin: https://www.linkedin.com/in/yuchen-zhang-b283a221a/
twitter: https://x.com/YuchenZE

# Images 
avatar: ./assets/img/resized.jpg
favicon: ./assets/img/icon.png
favicon_dark: ./assets/img/icon.png

# Footnotes
footnote: website's source code from Yaoyao Liu.
footnote_link: https://github.com/yaoyao-liu/yaoyao-liu.github.io

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
